Repository ERICA-Club-Hub/Backend, pull requests merged in 2025-03, with the labels that each got.

#64 ✨ [FEAT] 동아리 월 별 일정 임시저장 API 구현 및 조회 응답 값 수정
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/domain/draft/ClubDetailDraft.java
  src/main/java/kr/hanjari/backend/domain/draft/ScheduleDraft.java
  src/main/java/kr/hanjari/backend/repository/draft/ScheduleDraftRepository.java
  src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java
  src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubDetailRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/draft/ClubDetailDraftResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/draft/ClubIntroductionDraftResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/draft/ClubRecruitmentDraftResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/draft/ClubScheduleDraftResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/draft/ScheduleDraftResponseDTO.java
Labels: :sparkles: Feature, :recycle: Refactor

#67 ♻️ [REFACTOR] 로그인 응답 필드 추가
  src/main/java/kr/hanjari/backend/service/auth/AuthService.java
  src/main/java/kr/hanjari/backend/service/auth/impl/AuthServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/AuthController.java
  src/main/java/kr/hanjari/backend/web/dto/auth/LoginResultDTO.java
  src/main/java/kr/hanjari/backend/web/dto/auth/response/LoginResponseDTO.java
  src/main/resources/application.properties
Labels: :recycle: Refactor

#68 🐛 [FIX] 총동연 공지사항 수정/삭제 API 문제 해결
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/service/announcement/impl/AnnouncementServiceImpl.java
Labels: :bug: BugFix

#70 ♻️ [REFACTOR] 월 별 일정 응답 DTO 변수 명 `schedules`로 통일
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubScheduleResponseDTO.java
Labels: :recycle: Refactor

#72 ✨ [FEATURE] 등록 요청 동아리 조회 API 구현
  src/main/java/kr/hanjari/backend/config/SecurityConfig.java
  src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRegistrationDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/GetRegistrationsResponseDTO.java
Labels: :sparkles: Feature

#73 👷 [CHORE] profile 설정 및 cors 변경
  src/main/java/kr/hanjari/backend/config/CorsConfig.java
  src/main/java/kr/hanjari/backend/security/token/JwtUtil.java
  src/main/java/kr/hanjari/backend/service/auth/impl/AuthServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: :gear: Setting

#74 👷 [CHORE] cors 허용 origin 수정
  src/main/java/kr/hanjari/backend/config/CorsConfig.java
Labels: :gear: Setting

#75 👷 [CHORE] cors 설정 변경
  src/main/java/kr/hanjari/backend/config/CorsConfig.java
Labels: :gear: Setting

#76 🐛 [FIX] Swagger 오류 해결
  src/main/java/kr/hanjari/backend/config/CorsConfig.java
  src/main/java/kr/hanjari/backend/config/SwaggerConfig.java
Labels: :bug: BugFix

#77 ✨ [FEATURE] 동아리 등록 요청 수락 API
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ActivityController.java
  src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
Labels: :sparkles: Feature

#81 ✨ [FEATURE] 피드백 추가
  src/main/java/kr/hanjari/backend/domain/Feedback.java
  src/main/java/kr/hanjari/backend/repository/FeedbackRepository.java
  src/main/java/kr/hanjari/backend/service/activity/impl/ActivityServiceImpl.java
  src/main/java/kr/hanjari/backend/service/feedback/FeedbackService.java
  src/main/java/kr/hanjari/backend/service/feedback/impl/FeedbackServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ActivityController.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
  src/main/java/kr/hanjari/backend/web/controller/FeedbackController.java
  src/main/java/kr/hanjari/backend/web/dto/feedback/FeedbackDTO.java
Labels: :sparkles: Feature

#82 👷 [CHORE] prod 서버용 설정 추가
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
  dev-docker-compose.yml
  prod-docker-compose.yml
  src/main/java/kr/hanjari/backend/config/DevCorsConfig.java
  src/main/java/kr/hanjari/backend/config/ProdCorsConfig.java
  src/main/java/kr/hanjari/backend/config/SwaggerConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: :earth_asia: Infrastructure, :gear: Setting

#83 👷 [FIX] SSL 인증서 경로 수정
  dev-docker-compose.yml
  prod-docker-compose.yml
Labels: :gear: Setting

#84 [CHORE] CORS 허용 도메인 추가
  src/main/java/kr/hanjari/backend/config/DevCorsConfig.java
  src/main/java/kr/hanjari/backend/config/ProdCorsConfig.java
Labels: :earth_asia: Infrastructure, :gear: Setting

#86 🐛 [FIX] db, docker 버그 수정
  prod-docker-compose.yml
  src/main/resources/application-prod.properties
Labels: :bug: BugFix

#89 [CHORE] prod cors 허용 origin 제한
  src/main/java/kr/hanjari/backend/config/DevCorsConfig.java
  src/main/java/kr/hanjari/backend/config/ProdCorsConfig.java
Labels: :earth_asia: Infrastructure

#94 ✨ [FEATURE] 동아리 가입 승인 : 이메일 전송 기능 구현
  build.gradle
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/service/club/ClubUtil.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/templates/success.html
Labels: :sparkles: Feature

#95 [FIX] 동아리 등록 요청 수락 오류 수정
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
Labels: :bug: BugFix

#98 ✨ [FEATURE] clubId 검사 로직 추가
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/service/activity/impl/ActivityServiceImpl.java
  src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/s3/S3Service.java
  src/main/java/kr/hanjari/backend/service/s3/S3Util.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubBasicInformationDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/CommonClubDTO.java
Labels: :sparkles: Feature, :recycle: Refactor

#100 👷 [CHORE] swagger용 cors 허용 origin 추가
  src/main/java/kr/hanjari/backend/config/DevCorsConfig.java
Labels: :gear: Setting

#102 [FEATURE] 모니터링 추가
  build.gradle
  src/main/resources/application.properties
Labels: :earth_asia: Infrastructure, :gear: Setting

#105 ✨ [FEATURE] 로그 모니터링 추가
  prod-docker-compose.yml
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: :sparkles: Feature

#107 ✨ [FEATURE] 활동로그 수정 API 변경
  src/main/java/kr/hanjari/backend/domain/Activity.java
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/domain/ClubRegistration.java
  src/main/java/kr/hanjari/backend/domain/Document.java
  src/main/java/kr/hanjari/backend/domain/Introduction.java
  src/main/java/kr/hanjari/backend/domain/Recruitment.java
  src/main/java/kr/hanjari/backend/domain/Schedule.java
  src/main/java/kr/hanjari/backend/service/activity/impl/ActivityServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ActivityController.java
  src/main/java/kr/hanjari/backend/web/dto/activity/request/UpdateActivityRequest.java
Labels: :sparkles: Feature, :gear: Setting
