Repository ERICA-Club-Hub/Backend, pull requests merged in 2025-01, with the labels that each got.

#3 [ CHORE] CI/CD 및 프로젝트 세팅
  .gitignore
  Dockerfile
  HELP.md
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kr/hanjari/backend/BackendApplication.java
  src/main/java/kr/hanjari/backend/domain/Activity.java
  src/main/java/kr/hanjari/backend/domain/Announcement.java
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/domain/Document.java
  src/main/java/kr/hanjari/backend/domain/File.java
  src/main/java/kr/hanjari/backend/domain/Introduction.java
  src/main/java/kr/hanjari/backend/domain/Recruitment.java
  src/main/java/kr/hanjari/backend/domain/Schedule.java
  src/main/java/kr/hanjari/backend/domain/ServiceAnnouncement.java
  src/main/java/kr/hanjari/backend/domain/User.java
  src/main/java/kr/hanjari/backend/domain/common/BaseEntity.java
  src/main/java/kr/hanjari/backend/domain/enums/ClubCategory.java
  src/main/java/kr/hanjari/backend/domain/enums/RecruitmentStatus.java
  src/main/java/kr/hanjari/backend/domain/enums/Role.java
  src/main/java/kr/hanjari/backend/domain/key/ActivityImageId.java
  src/main/java/kr/hanjari/backend/domain/key/DocumentFileId.java
  src/main/java/kr/hanjari/backend/domain/key/ScheduleId.java
  src/main/java/kr/hanjari/backend/domain/mapping/ActivityImage.java
  src/main/java/kr/hanjari/backend/domain/mapping/DocumentFile.java
  src/main/java/kr/hanjari/backend/payload/ApiResponse.java
  src/main/java/kr/hanjari/backend/payload/code/BaseCode.java
  src/main/java/kr/hanjari/backend/payload/code/BaseErrorCode.java
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/payload/code/status/SuccessStatus.java
  src/main/java/kr/hanjari/backend/payload/dto/ErrorReasonDTO.java
  src/main/java/kr/hanjari/backend/payload/dto/ReasonDTO.java
  src/main/java/kr/hanjari/backend/payload/exception/ExceptionAdvice.java
  src/main/java/kr/hanjari/backend/payload/exception/GeneralException.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/kr/hanjari/backend/BackendApplicationTests.java
Labels: :earth_asia: Infrastructure, :gear: Setting

#6 🔧 [Chore] Swagger 세팅
  build.gradle
  src/main/java/kr/hanjari/backend/config/SwaggerConfig.java
Labels: :gear: Setting

#7 📝 [DOCS] 담당 기능 API 명세서 작성
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/controller/ServiceAnnouncementController.java
  src/main/java/kr/hanjari/backend/web/controller/UserController.java
  src/main/java/kr/hanjari/backend/web/dto/club/ClubRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/ClubResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/ServiceAnnouncementRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/ServiceAnnouncementResponseDTO.java
Labels: :page_facing_up: Docs

#12 ✨ [FEATURE] 동아리 상세 페이지 API 구현
  src/main/java/kr/hanjari/backend/domain/Activity.java
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/domain/Introduction.java
  src/main/java/kr/hanjari/backend/domain/Recruitment.java
  src/main/java/kr/hanjari/backend/domain/Schedule.java
  src/main/java/kr/hanjari/backend/domain/enums/SortBy.java
  src/main/java/kr/hanjari/backend/domain/key/ActivityImageId.java
  src/main/java/kr/hanjari/backend/domain/key/DocumentFileId.java
  src/main/java/kr/hanjari/backend/domain/key/ScheduleId.java
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/repository/ActivityRepository.java
  src/main/java/kr/hanjari/backend/repository/ClubRepository.java
  src/main/java/kr/hanjari/backend/repository/IntroductionRepository.java
  src/main/java/kr/hanjari/backend/repository/RecruitmentRepository.java
  src/main/java/kr/hanjari/backend/repository/ScheduleRepository.java
  src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java
  src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/dto/club/ClubRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/ClubResponseDTO.java
Labels: :sparkles: Feature

#13 ✨ [FEATURE] 서비스 공지사항 API 구현
  src/main/java/kr/hanjari/backend/BackendApplication.java
  src/main/java/kr/hanjari/backend/domain/ServiceAnnouncement.java
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/repository/ServiceAnnouncementRepository.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/ServiceAnnouncementCommandService.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/ServiceAnnouncementQueryService.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/impl/ServiceAnnouncementCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/impl/ServiceAnnouncementQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ServiceAnnouncementController.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/ServiceAnnouncementResponseDTO.java
Labels: :sparkles: Feature

#14 📝 [DOCS] 담당 API 명세서 작성
  src/main/java/kr/hanjari/backend/web/controller/ActivityController.java
  src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
  src/main/java/kr/hanjari/backend/web/dto/activity/ActivityRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/announcement/AnnouncementRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/ClubRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/document/DocumentRequestDTO.java
Labels: :page_facing_up: Docs

#18 ✨ [FEATURE] 어드민 로그인&로그아웃 API 구현
  build.gradle
  src/main/java/kr/hanjari/backend/config/RedisConfig.java
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/repository/ClubRepository.java
  src/main/java/kr/hanjari/backend/security/auth/JwtTokenProvider.java
  src/main/java/kr/hanjari/backend/service/user/UserCommandService.java
  src/main/java/kr/hanjari/backend/service/user/impl/UserCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/UserController.java
  src/main/java/kr/hanjari/backend/web/dto/user/request/UserLoginRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/user/response/UserCodeResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/user/response/UserLoginResponseDTO.java
  src/main/resources/application.properties
Labels: :sparkles: Feature

#16 ✨ [FEATURE] 자료실 기능 구현
  build.gradle
  src/main/java/kr/hanjari/backend/domain/Document.java
  src/main/java/kr/hanjari/backend/domain/File.java
  src/main/java/kr/hanjari/backend/domain/key/DocumentFileId.java
  src/main/java/kr/hanjari/backend/domain/mapping/DocumentFile.java
  src/main/java/kr/hanjari/backend/repository/DocumentFileRepository.java
  src/main/java/kr/hanjari/backend/repository/DocumentRepository.java
  src/main/java/kr/hanjari/backend/repository/FileRepository.java
  src/main/java/kr/hanjari/backend/service/document/DocumentService.java
  src/main/java/kr/hanjari/backend/service/document/impl/DocumentServiceImpl.java
  src/main/java/kr/hanjari/backend/service/s3/S3Service.java
  src/main/java/kr/hanjari/backend/service/s3/S3UtilService.java
  src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
  src/main/java/kr/hanjari/backend/web/dto/document/DocumentDTO.java
  src/main/java/kr/hanjari/backend/web/dto/document/DocumentRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/document/request/CreateDocumentRequest.java
  src/main/java/kr/hanjari/backend/web/dto/document/request/UpdateDocumentRequest.java
  src/main/java/kr/hanjari/backend/web/dto/document/response/GetAllDocumentsResponse.java
  src/main/java/kr/hanjari/backend/web/dto/document/response/GetDocumentFilesResponse.java
  src/main/java/kr/hanjari/backend/web/dto/file/FileDTO.java
  src/main/resources/application.properties
Labels: :sparkles: Feature, :gear: Setting

#20 :recycle: [REFACTOR] DTO 패키지 구조 수정 및 Record로 변경
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/domain/Introduction.java
  src/main/java/kr/hanjari/backend/domain/Recruitment.java
  src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java
  src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/ServiceAnnouncementCommandService.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/ServiceAnnouncementQueryService.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/impl/ServiceAnnouncementCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/impl/ServiceAnnouncementQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/controller/ServiceAnnouncementController.java
  src/main/java/kr/hanjari/backend/web/dto/club/ClubRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/ClubResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubDetailRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubIntroductionRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubRecruitmentRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubScheduleRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/CommonClubDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubDetailResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubIntroductionResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRecruitmentResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubScheduleResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubSearchResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ScheduleResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/ServiceAnnouncementRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/ServiceAnnouncementResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/request/CreateServiceAnnouncementRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/response/ServiceAnnouncementDetailDTO.java
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/response/ServiceAnnouncementSearchDTO.java
Labels: :recycle: Refactor
