Repository ERICA-Club-Hub/Backend, pull requests merged in 2025-02, with the labels that each got.

#23 ✨ [FEATURE] 총동연 공지사항 기본 기능 구현
  src/main/java/kr/hanjari/backend/domain/Announcement.java
  src/main/java/kr/hanjari/backend/repository/AnnouncementRepository.java
  src/main/java/kr/hanjari/backend/service/announcement/AnnouncementService.java
  src/main/java/kr/hanjari/backend/service/announcement/impl/AnnouncementServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java
  src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
  src/main/java/kr/hanjari/backend/web/dto/announcement/AnnouncementRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/announcement/request/CommonAnnouncementRequest.java
  src/main/java/kr/hanjari/backend/web/dto/announcement/response/AnnouncementDTO.java
  src/main/java/kr/hanjari/backend/web/dto/announcement/response/GetAllAnnouncementResponse.java
  src/main/resources/application.properties
Labels: :page_facing_up: Docs, :sparkles: Feature

#24 :sparkles: [FEATURE] 동아리 검색 API 구현
  src/main/java/kr/hanjari/backend/domain/enums/SortBy.java
  src/main/java/kr/hanjari/backend/repository/ClubRepository.java
  src/main/java/kr/hanjari/backend/repository/specification/ClubSpecifications.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubSearchResponseDTO.java
Labels: :sparkles: Feature

#31 ✨[FEATURE] 인증/인가 적용
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/repository/ClubRepository.java
  src/main/java/kr/hanjari/backend/security/auth/JwtTokenProvider.java
  src/main/java/kr/hanjari/backend/service/activity/impl/ActivityServiceImpl.java
  src/main/java/kr/hanjari/backend/service/announcement/impl/AnnouncementServiceImpl.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/document/impl/DocumentServiceImpl.java
  src/main/java/kr/hanjari/backend/service/serviceAnnouncement/impl/ServiceAnnouncementCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/user/UserCommandService.java
  src/main/java/kr/hanjari/backend/service/user/impl/UserCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubSearchResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/user/response/UserLoginResponseDTO.java
  src/main/resources/application.properties
Labels: :sparkles: Feature

#33 🚑️ [FIX] CORS 해결
  src/main/java/kr/hanjari/backend/web/controller/ActivityController.java
  src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java
  src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
Labels: :bug: BugFix

#34 ✨ [FEATURE] 동아리 등록 관련 기능 구현
  src/main/java/kr/hanjari/backend/domain/Activity.java
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/domain/ClubRegistration.java
  src/main/java/kr/hanjari/backend/domain/File.java
  src/main/java/kr/hanjari/backend/repository/ClubRegistrationRepository.java
  src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/controller/DocumentController.java
  src/main/java/kr/hanjari/backend/web/controller/HealthCheckController.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/CommonClubDTO.java
Labels: :sparkles: Feature

#36 ♻️ [REFACTOR] JWT 응답 방식 Body에서 Header로 변경
  src/main/java/kr/hanjari/backend/service/user/UserCommandService.java
  src/main/java/kr/hanjari/backend/service/user/impl/UserCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/UserController.java
  src/main/java/kr/hanjari/backend/web/dto/user/response/UserLoginResponseDTO.java
Labels: :recycle: Refactor

#40 :bug: [FIX] 서비스 공지사항 페이징 조회 시, 정확한 갯수 반환하도록 수정
  src/main/java/kr/hanjari/backend/web/dto/serviceAnnouncement/response/ServiceAnnouncementSearchDTO.java
Labels: :bug: BugFix

#42 ✨ [FEATURE] 동아리 소개글, 모집 안내 임시저장 API 구현
  src/main/java/kr/hanjari/backend/domain/draft/IntroductionDraft.java
  src/main/java/kr/hanjari/backend/domain/draft/RecruitmentDraft.java
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/repository/draft/IntroductionDraftRepository.java
  src/main/java/kr/hanjari/backend/repository/draft/RecruitmentDraftRepository.java
  src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java
  src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubIntroductionRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubIntroductionDraftResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRecruitmentDraftResponseDTO.java
Labels: :sparkles: Feature

#45 :bug: [FIX] Health Check API CORS 해결
  src/main/java/kr/hanjari/backend/web/controller/HealthCheckController.java
Labels: :bug: BugFix

#49 ♻ [REFACTOR] 동아리 소개글, 모집 안내 응답 로직 수정
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubDetailRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubIntroductionResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRecruitmentResponseDTO.java
Labels: :recycle: Refactor

#52 ♻ [REFACTOR] 관리자 네이밍 통일 및 누락된 Enum 추가
  src/main/java/kr/hanjari/backend/config/SecurityConfig.java
  src/main/java/kr/hanjari/backend/domain/enums/ClubCategory.java
  src/main/java/kr/hanjari/backend/domain/enums/Role.java
  src/main/java/kr/hanjari/backend/security/token/JwtUtil.java
  src/main/java/kr/hanjari/backend/web/controller/AnnouncementController.java
  src/main/java/kr/hanjari/backend/web/controller/AuthController.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
Labels: :recycle: Refactor

#54 👷 [CHORE] nginx 추가
  docker-compose.yml
Labels: :gear: Setting

#55 [FIX] 헤더 보이도록 애노테이션 옵션 추가
  src/main/java/kr/hanjari/backend/web/controller/AuthController.java
Labels: :bug: BugFix

#57 :sparkles: [FEATURE] 동아리 대표 이미지 관련 API 구현
  src/main/java/kr/hanjari/backend/domain/Club.java
  src/main/java/kr/hanjari/backend/domain/draft/ClubDetailDraft.java
  src/main/java/kr/hanjari/backend/payload/code/status/ErrorStatus.java
  src/main/java/kr/hanjari/backend/repository/draft/ClubDetailDraftRepository.java
  src/main/java/kr/hanjari/backend/service/club/ClubCommandService.java
  src/main/java/kr/hanjari/backend/service/club/ClubQueryService.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubCommandServiceImpl.java
  src/main/java/kr/hanjari/backend/service/club/impl/ClubQueryServiceImpl.java
  src/main/java/kr/hanjari/backend/web/controller/ClubController.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/ClubDetailRequestDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/request/CommonClubDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubDetailDraftResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubIntroductionResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubRecruitmentResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubResponseDTO.java
  src/main/java/kr/hanjari/backend/web/dto/club/response/ClubSearchResponseDTO.java
Labels: :sparkles: Feature
